import CounterTemplate from '@/templates/counter'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Counter Page",
    description: "Generated by create next app",
};

const page = () => {
  return (
      <CounterTemplate />
  )
}

export default page
