export const ENV = {
    NODE_ENV: process.env.NODE_ENV,
    PREDICTHQ_API_URL: process.env.PREDICTHQ_API_URL,
    PREDICTHQ_API_ACCESS_TOKEN: process.env.PREDICTHQ_API_ACCESS_TOKEN,
    IPSTACK_ACCESS_TOKEN: process.env.IPSTACK_ACCESS_TOKEN,
    APP_API_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
}
