import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import { ThemeProvider } from "@/context/ThemeContext";
import { IChildren } from "@/types";
import Header from "@/organisms/Header";
import ThemeToggle from "@/molecules/ThemeToggle";
import Footer from "@/organisms/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: IChildren;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <ThemeProvider>
            <Header />
            <main className="pt-[80px]">
              {children}
            </main>
            <Footer />
            <ThemeToggle />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
